import Head from "next/head";
import View from "../components/view";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chakra UI App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <View />
      </main>
    </div>
  );
}
